#test
pipeline:
  build:
    image: plugins/docker
    repo: bgulla/drone-http-test
#    repo: harbor.lol/dev/http-server
#    registry: harbor.lol
    tags: 
      - 1.0.0
      - 1.0
      - latest
image_pull_secrets:
- dockercfg
