#test
pipeline:
  build:
    image: plugins/docker
    #repo: bgulla/drone-http-test
    repo: harbor.lol/dev/http-server
    registry: harbor-harbor-registry.infra:8080
    insecure: true
#    insecure: true
#    registry: harbor.lol:443
    tags: 
      - 1.0.0
      - 1.0
      - latest
    insecure: true
image_pull_secrets:
- dockercfg
